services:
  neo4j:
    image: neo4j:latest
    container_name: db_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/var/lib/neo4j/data
      - neo4j_logs:/var/lib/neo4j/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  idt-api:
    build: ../api
    container_name: idt_api
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - 8002:80
    environment:
      - DB_URL=neo4j://neo4j:7687
      - DB_USERNAME=neo4j
      - DB_PASSWORD=password

volumes:
  neo4j_data:
  neo4j_logs:
