name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/api
          pytest api/tests/

  image-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    needs: test
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set environment variables
        run: |
          echo "ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV
        
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} -f api/Dockerfile
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_NAME }}:latest
        
      #- name: Push Docker image to ECR
      #  run: |          
      #    docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_NAME }}:latest
